---
#
# Ansible managed
#
repository:
  description: Install and configure glusterfs on your system.
  homepage: https://robertdebock.nl/
  topics: cluster, gluster, glusterfs, server, system, ansible, molecule, tox, playbook, hacktoberfest
