---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="30"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "DK/1n+u8NrpXllBAHphKiSPZKSBD3WBlxDpHwEd8/3C4ZKDuooJLI45YeQw8hHv1n8gIFDEHkLQhy1nvvF/x0HMLJsPJJN/qZLuR7mdeScjvCuv7W8xoW14VUDERS4ooakA3EV7waXS4krd/SwO3bjBMDoj3YxmV7I3dSO8XAF45sBoKWh/YnQ0n+4+s21MYJenwQ5Kr8fXq0+MGxDiZUBlO85/mG0BLl69cD3aezp7flbI7p4Jt/kZn2pdrsZVKUKmXaqLLhA4KftLB+z8JUQ5U2RcdCsH1N+t7bxNrSAvi9hPUL6IyVj+uK/XaJALt2EgihrO6Ksm7m2D7Dh9i9WuNPoNNn8MuIWu3BkhogDDXVlx88MHKxNSmtvvG0lQlZ7G6Z/Jb1ZGcOYCT/rCQNqkRFlGzI0CgwNnsLErx8ArSZjFVc+AYPKDRKzrSGPSbPlE7hG/nelw/UVJOPxRnCB+gpKVvDPZy6lUm8T5tVIQ8XDRb0Fq/VtgpTB+VXAwavm518E/X3JEnrR++rIghZ+qe6Iqgl3S0h072ERGJTkE9JsM/mecmmSduAiR0+EB4tK2o/HvpW9hruChzAY5hu6gz+qvlGZAp0CWV6oDywtNl4miXHIy/U7RXWUDGe8tEqcGXqiPvu9JC7Su2RYXJonBHnC187Oh+n/ThFrCgwjU="
  email: false
