---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: glusterfs-ubuntu-rolling
    image: ubuntu:rolling
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        glusterfs_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-rolling
verifier:
  name: goss
  lint:
    name: yamllint
