---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    glusterfs_bricks:
      - name: brick1
        device: /dev/vdb
        mountpoint: /data/brick1

    glusterfs_volumes:
      - name: gv0
        bricks: /data/brick1/gv0
        replicas: 3
        mountpoint: /mnt/gv0
        rebalance: no

  roles:
    - robertdebock.bootstrap
    - robertdebock.apt_autostart
    - ansible-role-glusterfs
